spring:
  datasource:
    password: ${MYSQL_PASSWORD:AVNS_5GWHdTOJYYtGPhYHza9}
    url: jdbc:mysql://${MYSQL_HOST:db-mysql-nyc3-18222-do-user-15957682-0.c.db.ondigitalocean.com}:${MYSQL_PORT:25060}/${MYSQL_DATABASE:nabd}
    username: doadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
JWT_SECRET_KEY: 931949128c37ce0092f6eb8fc450f6e844f19103c6c626683437e76cef3bd855
