spring:
  datasource:
    password: ${MYSQL_PASSWORD:hTPC22d7scPF*Vg}
    url: jdbc:mysql://${MYSQL_HOST:sql.freedb.tech}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:freedb_nabddb}
    username: freedb_nabddb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
JWT_SECRET_KEY: 931949128c37ce0092f6eb8fc450f6e844f19103c6c626683437e76cef3bd855
