spring:
  datasource:
    password: ${MYSQL_PASSWORD:admin}
    url: jdbc:mysql://${MYSQL_HOST:172.30.121.217}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:nabd}
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

JWT_SECRET_KEY: 931949128c37ce0092f6eb8fc450f6e844f19103c6c626683437e76cef3bd855